### ISSUE TITLE
Round2: After playing 1 round, when starting round 2, the new decider is assigned a stakeholder role.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#85]
You can see that every player is able to open the rolecard and see a new role. 

![screen shot 2017-04-04 at 8 42 38 pm](https://cloud.githubusercontent.com/assets/10051544/24685857/2a22115e-197e-11e7-88a8-44145ed57624.png)

It SEEMS like this does not break anything from my one test in, but I'm not sure. Either way, this could cause confusion for players.

**Comment by johnnycrich** [comment]
@jpailthorpe Is this resolved by hiding the role card button for the decider (we are doing this now)?

**Comment by jpailthorpe** [comment]
@johnny this is actually most likely related to why we couldn't play past round 1 today. When the decider from round 1 goes into round 2, they aren't able to see a role card button. The bottom bar component is not updated and therefore they don't know which role they are playing. So basically we just need to make sure these player role assignments are lined up with the component visibility.

**Comment by jpailthorpe** [comment]
Technically we could continue to play the game ie. It didn't stop us, but from a ux perspective it would not have made any sense

**Comment by jpailthorpe** [comment]
When this is QAed, if not resolved, please moe back to backlog and to the top of the queue. This is priority if not fixed!

**Comment by jpailthorpe** [comment]
verified this is fixed.
